services:
  db:
    image: postgres:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
      - ./config/certs:/app/config/certs
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:  # 追加した部分
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/app
      - ./config/certs:/app/config/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444

volumes:
  postgres_data:
  bundle_data:
  node_modules: